name    'ispavailability-beaver'
version '0.0.3'
source 'https://github.com/electrical/puppet-beaver'
author 'ispavailability'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring beaver'
description 'Module for managing and configuring beaver'
project_page 'https://github.com/electrical/puppet-beaver'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'ispavailability/file_concat', '>= 0.0.1'
